### PR TITLE
Fix connection never timing out for ice-lite

### LINKED ISSUE #35: ICE agent in ice-lite never times out
If an ICE agent doesn't receive _any UDP traffic at all_. I..e. no candidate is ever nominated, the agent never times out at all.

That means we get forever hanging clients when there is no UDP connectivity.

### PR DESCRIPTION
**Pull request by algesten**
Close #35

### CODE REVIEW

File: ice/src/agent.rs [hunk 1]
```diff
@@ -827,6 +827,16 @@ impl IceAgent {
         }
 
         if self.ice_lite {
+            // Remote binding request time is the timestamp in the CandidatePair that
+            // is used to decide whether something is timed out or not. We need all
+            // pairs to have this time set, so that pairs that don't receive any
+            // STUN binding requests eventually times out.
+            for p in &mut self.candidate_pairs {
+                if !p.remote_binding_request_time().is_some() {
```
Comment (k0nserv) [inline ice/src/agent.rs:835]: `p.remote_binding_request_time().is_none()`

**Review by k0nserv — APPROVED** [review]

File: ice/src/agent.rs (hunk 1 above)
Comment (algesten) [reply ice/src/agent.rs:835]: good point! :)
